# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  Vagrant.configure("2") do |config|
    config.vagrant.plugins = "vagrant-libvirt"
  end

  config.vm.define "kvmserver1" do |kvmserver1|
    kvmserver1.vm.box = "centos/7"
    kvmserver1.vm.hostname = "kvmserver1"
    #kvmserver1.vm.network "private_network", type: "dhcp"
    kvmserver1.vm.provision "shell", inline: <<-SHELL
      yum -y group install "Virtualization Host"
      systemctl start libvirtd
      systemctl enable libvirtd
      sudo usermod -a -G libvirt vagrant #необходимо, чтобы подключаться к либвирту с хоста
      echo $(ip -4 -br a show eth0 | awk '{print $3}')
    SHELL
  end
end