# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  Vagrant.configure("2") do |config|
    config.vagrant.plugins = "vagrant-libvirt"
  end

  config.vm.define "ftpserver" do |ftpserver|
    ftpserver.vm.box = "centos/7"
    ftpserver.vm.hostname = "ftpserver"
    #ftpserver.vm.network "private_network", type: "dhcp"
    ftpserver.vm.provision "shell", inline: <<-SHELL
      yum -y install vsftpd
      #echo ID_RSA_PUB >> /home/vagrant/.ssh/authorized_keys
      systemctl start vsftpd
      systemctl enable vsftpd
      mount -ro loop /vagrant/CentOS-7-x86_64-Minimal-2009.iso /media
      mkdir /var/ftp/pub/inst
      cp -a /media/* /var/ftp/pub/inst
      chcon -R -t public_content_t /var/ftp/pub/
      echo $(ip -4 -br a show eth0 | awk '{print $3}')
    SHELL
  end
  
end
