# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vagrant.plugins = {"vagrant-vbguest" => {"version" => "0.21.0"}}
  config.vbguest.installer_options = { allow_kernel_upgrade: true } 

  config.vm.provider :virtualbox do |vbox|
    vbox.check_guest_additions = false
    vbox.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
  end

  config.vm.define "ftpserver1" do |ftpserver1|
    ftpserver1.vm.provider :virtualbox do |vbox|
      vbox.memory = 1024
      vbox.cpus = 1
    end
    ftpserver1.vm.box = "centos/7"
    ftpserver1.vm.hostname = "ftpserver1"
    ftpserver1.vm.network "private_network", type: "dhcp"
    #ftpserver1.vm.synced_folder "volume/", "/srv/vagrant"
    ftpserver1.vm.synced_folder "volume/", "/var/ftp/pub/"
    ftpserver1.vm.provision "shell", inline: <<-SHELL
      yum -y install vsftpd
      #echo ID_RSA_PUB >> /home/vagrant/.ssh/authorized_keys
      systemctl start vsftpd
      systemctl enable vsftpd
    SHELL
  end

end