# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.ssh.private_key_path = '/root/.ssh/id_rsa'
  (1..3).each do |i|
    config.vm.define "vm#{i}" do |node|
    end
  end
end
