# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos7mykey"
  config.vm.define "router1"
  config.vm.synced_folder '.', '/vagrant', disabled: true
end
